import { defineGame } from "@merky/game-sdk";
import {
  initTileTangle,
  reduceTileTangle,
  onTickTileTangle,
  onSeatAbandonedTileTangle,
  awaitedSeatsTileTangle,
  suggestBotActionTileTangle,
} from "./logic";
import { Stage } from "./Stage";
import { Controller } from "./Controller";

export const tiletangle = defineGame({
  meta: {
    id: "tiletangle",
    nameKey: "games.tiletangle.name",
    descriptionKey: "games.tiletangle.description",
    minPlayers: 2,
    maxPlayers: 8,
    supportsSpectators: true,
    supportsMidGameJoin: true,
    tags: ["tiles", "turn-based", "brainy"],
    defaultSettings: { turnSeconds: 90, initialMeldPoints: 30 },
    settingFields: [
      {
        key: "turnSeconds",
        labelKey: "games.tiletangle.setting.turnSeconds",
        type: "number",
        default: 90,
        min: 30,
        max: 180,
        step: 15,
      },
      {
        key: "initialMeldPoints",
        labelKey: "games.tiletangle.setting.initialMeldPoints",
        type: "number",
        default: 30,
        min: 20,
        max: 40,
        step: 5,
      },
    ],
  },
  i18n: {
    en: {
      "games.tiletangle.name": "Tile Tangle",
      "games.tiletangle.description": "Lay sets and runs, retangle the table, empty your rack first.",
      "games.tiletangle.setting.turnSeconds": "Turn Duration (seconds)",
      "games.tiletangle.setting.initialMeldPoints": "Initial Meld Requirement (points)",
      "games.tiletangle.yourTurn": "It's your turn!",
      "games.tiletangle.waitingFor": "Waiting for {name}...",
      "games.tiletangle.drawTile": "Draw Tile",
      "games.tiletangle.playTiles": "Play Tiles",
      "games.tiletangle.reset": "Reset Table",
      "games.tiletangle.newMeld": "+ New Meld",
      "games.tiletangle.returnToRack": "Return to Rack",
      "games.tiletangle.sort789": "1-2-3",
      "games.tiletangle.sortColor": "Color 🎨",
      "games.tiletangle.moveLeft": "◀ Left",
      "games.tiletangle.moveRight": "Right ▶",
      "games.tiletangle.initialMeldMeter": "New tiles total: {current} / {target}",
      "games.tiletangle.notMeldedYet": "Not melded yet",
      "games.tiletangle.hasMelded": "Melded",
      "games.tiletangle.drawPile": "Draw Pile",
      "games.tiletangle.emptyTable": "Table is empty",
      "games.tiletangle.yourRack": "Your Rack",
      "games.tiletangle.tableMelds": "Table Melds",
      "games.tiletangle.gameOver": "Game Over",
      "games.tiletangle.winnerAnnouncement": "{name} wins!",
      "games.tiletangle.turnNotice": "Turn: {name}",
      "games.tiletangle.err.not_your_turn": "Not your turn",
      "games.tiletangle.err.bad_phase": "Game is not in turn phase",
      "games.tiletangle.err.invalid_meld": "One or more melds are invalid",
      "games.tiletangle.err.tiles_not_conserved": "Table tiles must equal old table plus placed tiles",
      "games.tiletangle.err.not_in_rack": "Placed tile is not in your rack",
      "games.tiletangle.err.nothing_placed": "You must place at least one tile",
      "games.tiletangle.err.initial_meld_too_low": "Initial meld must total at least {target} points",
      "games.tiletangle.err.cannot_rearrange_before_meld": "Cannot rearrange table tiles before your initial meld",
    },
  },
  init: initTileTangle,
  reduce: reduceTileTangle,
  onTick: onTickTileTangle,
  onSeatAbandoned: onSeatAbandonedTileTangle,
  awaitedSeats: awaitedSeatsTileTangle,
  suggestBotAction: suggestBotActionTileTangle,
  ui: {
    Stage,
    Controller,
  },
});
