import type { ContentPack } from "@merky/game-sdk";

export const ZAPLASH_CORE_PROMPTS: string[] = [
  "The real reason aliens haven't visited Earth yet: _____",
  "A terrible name for a gourmet soup restaurant: _____",
  "What grandma really does when she says she's 'napping': _____",
  "The worst thing to hear right before surgery: _____",
  "What is secretly powering the internet? _____",
  "A rejected slogan for a theme park: _____",
  "The secret ingredient in cafeteria chili: _____",
  "What cats are actually thinking when they stare at a blank wall: _____",
  "The worst item to bring to a potluck: _____",
  "A bad excuse for being three hours late to your wedding: _____",
  "What Santa does during his off-season in July: _____",
  "The ultimate punishment in superhero prison: _____",
  "A completely useless superpower to get from a radioactive spider: _____",
  "The worst thing to say during a job interview at NASA: _____",
  "What really happened to the lost city of Atlantis: _____",
  "An awful gift for a 5-year-old's birthday: _____",
  "The weirdest thing to find inside a fortune cookie: _____",
  "A terrible title for a children's bedtime story: _____",
  "What dogs dream about during afternoon naps: _____",
  "The worst tagline for a dentist's office: _____",
  "What you shouldn't yell while riding a roller coaster: _____",
  "A bizarre reason to call 911: _____",
  "The secret ritual to summon a customer service representative: _____",
  "The worst candidate to run for Mayor of a small town: _____",
  "What time travelers are forbidden from changing in history: _____",
  "A terrible subject line for an email to your boss: _____",
  "What really goes on inside the Bermuda Triangle: _____",
  "The worst thing to discover under your hotel bed: _____",
  "A ridiculous requirement for joining a secret society: _____",
  "What ghosts do when no one is around to haunt: _____",
  "The worst topping to put on a luxury pizza: _____",
  "What high school gym teachers do on weekends: _____",
  "A terrible motto for a fortune 500 tech company: _____",
  "The most embarrassing thing to dropped during a quiet ceremony: _____",
  "What pigeons are secretly conspiring to do: _____",
  "The worst excuse for losing your passport in a foreign country: _____",
  "A terrible bumper sticker for a luxury sports car: _____",
  "What robots will demand when they take over: _____",
  "The worst thing to find in a sealed ancient Egyptian tomb: _____",
  "A terrible nickname for a professional boxer: _____",
  "What wizards do when they run out of mana: _____",
  "The worst theme for a high school prom: _____",
  "What to say to break a awkward silence in an elevator: _____",
  "The most suspicious thing to carry through airport security: _____",
  "A awful title for a self-help book: _____",
  "What squirrels are hiding in their secret underground bunkers: _____",
  "The worst advice to give a first-time marathon runner: _____",
  "What pirate captains complain about behind closed doors: _____",
  "A terrible replacement for money in the post-apocalypse: _____",
  "The worst thing to say after knocking over a display at an museum: _____",
  "What happens if you press the secret red button in the White House: _____",
  "A bizarre warning sign to put in your front yard: _____",
  "The worst flavor for a wellness smoothie: _____",
  "What vampires do when they get bored of immortality: _____",
  "A terrible feature to add to a smart refrigerator: _____",
  "The most unhelpful thing a tour guide could say: _____",
  "What really causes mystery noises in old houses: _____",
  "The worst song to play during a dramatic entrance: _____",
  "A hilarious side effect of a new energy drink: _____",
  "What aliens will put in the Earth museum exhibit: _____"
];

export const ZAPLASH_AFTERDARK_PROMPTS: string[] = [
  "The worst thing to say right after intimacy: _____",
  "A terrible confession to make on a first date: _____",
  "What your partner's search history really looks like: _____",
  "The worst place to leave a pair of dirty underwear: _____",
  "A terrible secret to reveal during truth or dare: _____",
  "The most awkward moment to get a sudden text message: _____",
  "What you shouldn't whisper in someone's ear at a club: _____",
  "A terrible name for a romance novel chapter: _____",
  "What's hidden in the bottom drawer of your nightstand: _____",
  "The worst excuse for getting caught sneaking out at 2 AM: _____",
  "A terrible pickup line to use at a funeral: _____",
  "What your ex is probably doing right now: _____",
  "The most inappropriate song to play on date night: _____",
  "A terrible tattoo to get on your lower back: _____",
  "The worst response to 'I love you': _____",
  "What you shouldn't bring into a hot tub party: _____",
  "A terrible theme for an adult birthday party: _____",
  "The worst thing to overhear through thin hotel walls: _____",
  "What really happens at bachelor parties when the phone cameras off: _____",
  "A bizarre reason to break up with someone after 3 years: _____",
  "The worst topic to bring up at Thanksgiving dinner with the in-laws: _____",
  "What your browser's incognito tab is ashamed of: _____",
  "A terrible nickname your partner calls you in private: _____",
  "The worst thing to drop in a public sauna: _____",
  "A terrible lie to tell on your dating app profile: _____",
  "What you shouldn't do during a couple's massage: _____",
  "The most awkward thing to find in your roommate's closet: _____",
  "A terrible line to use in a breakup text: _____",
  "What people are actually doing on video calls when camera is off: _____",
  "The worst thing to say to your partner's parents on first meeting: _____",
  "A terrible excuse for calling your boss by your spouse's name: _____",
  "The most suspicious stain to find on a couch cushion: _____",
  "What you shouldn't google on your work computer: _____",
  "A terrible gift to give your spouse on your anniversary: _____",
  "The worst thing to wear to a Speed Dating event: _____",
  "What your therapist is secretly writing down during your session: _____",
  "A terrible advice column answer for a broken heart: _____",
  "The most embarrassing object to buy at 3 AM from a 24-hour pharmacy: _____",
  "What you shouldn't say when caught looking at someone's photo: _____",
  "The worst way to propose marriage in public: _____"
];

export const zaplashPacks: ContentPack[] = [
  {
    id: "zaplash-core",
    gameId: "zaplash",
    titleKey: "games.zaplash.packs.core",
    locale: "en",
    nsfw: false,
    payload: { prompts: ZAPLASH_CORE_PROMPTS },
  },
  {
    id: "zaplash-afterdark",
    gameId: "zaplash",
    titleKey: "games.zaplash.packs.afterdark",
    locale: "en",
    nsfw: true,
    payload: { prompts: ZAPLASH_AFTERDARK_PROMPTS },
  },
];
