import type { ContentPack } from "@merky/game-sdk";

export const ZAPLASH_CORE_PROMPTS: string[] = [
  "The real reason aliens haven't visited Earth yet: _____",
  "A terrible name for a gourmet soup restaurant: _____",
  "What grandma really does when she says she's 'napping': _____",
  "The worst thing to hear right before surgery: _____",
  "What is secretly powering the internet? _____",
  "A rejected slogan for a theme park: _____",
  "The secret ingredient in cafeteria chili: _____",
  "What cats are actually thinking when they stare at a blank wall: _____",
  "The worst item to bring to a potluck: _____",
  "A bad excuse for being three hours late to your wedding: _____",
  "What Santa does during his off-season in July: _____",
  "The ultimate punishment in superhero prison: _____",
  "A completely useless superpower to get from a radioactive spider: _____",
  "The worst thing to say during a job interview at NASA: _____",
  "What really happened to the lost city of Atlantis: _____",
  "An awful gift for a 5-year-old's birthday: _____",
  "The weirdest thing to find inside a fortune cookie: _____",
  "A terrible title for a children's bedtime story: _____",
  "What dogs dream about during afternoon naps: _____",
  "The worst tagline for a dentist's office: _____",
  "What you shouldn't yell while riding a roller coaster: _____",
  "A bizarre reason to call 911: _____",
  "The secret ritual to summon a customer service representative: _____",
  "The worst candidate to run for Mayor of a small town: _____",
  "What time travelers are forbidden from changing in history: _____",
  "A terrible subject line for an email to your boss: _____",
  "What really goes on inside the Bermuda Triangle: _____",
  "The worst thing to discover under your hotel bed: _____",
  "A ridiculous requirement for joining a secret society: _____",
  "What ghosts do when no one is around to haunt: _____",
  "The worst topping to put on a luxury pizza: _____",
  "What high school gym teachers do on weekends: _____",
  "A terrible motto for a fortune 500 tech company: _____",
  "The most embarrassing thing to dropped during a quiet ceremony: _____",
  "What pigeons are secretly conspiring to do: _____",
  "The worst excuse for losing your passport in a foreign country: _____",
  "A terrible bumper sticker for a luxury sports car: _____",
  "What robots will demand when they take over: _____",
  "The worst thing to find in a sealed ancient Egyptian tomb: _____",
  "A terrible nickname for a professional boxer: _____",
  "What wizards do when they run out of mana: _____",
  "The worst theme for a high school prom: _____",
  "What to say to break a awkward silence in an elevator: _____",
  "The most suspicious thing to carry through airport security: _____",
  "A awful title for a self-help book: _____",
  "What squirrels are hiding in their secret underground bunkers: _____",
  "The worst advice to give a first-time marathon runner: _____",
  "What pirate captains complain about behind closed doors: _____",
  "A terrible replacement for money in the post-apocalypse: _____",
  "The worst thing to say after knocking over a display at an museum: _____",
  "What happens if you press the secret red button in the White House: _____",
  "A bizarre warning sign to put in your front yard: _____",
  "The worst flavor for a wellness smoothie: _____",
  "What vampires do when they get bored of immortality: _____",
  "A terrible feature to add to a smart refrigerator: _____",
  "The most unhelpful thing a tour guide could say: _____",
  "What really causes mystery noises in old houses: _____",
  "The worst song to play during a dramatic entrance: _____",
  "A hilarious side effect of a new energy drink: _____",
  "What aliens will put in the Earth museum exhibit: _____",
  "The real reason your Wi-Fi cuts out at the worst possible moment: _____",
  "A terrible name for a new ice cream flavor: _____",
  "What your houseplant is thinking right before it dies: _____",
  "The worst thing to hear from your pilot mid-flight: _____",
  "A bad excuse for showing up to school in pajamas: _____",
  "What librarians whisper about when the lights go out: _____",
  "The worst mascot for a cereal brand: _____",
  "A ridiculous rule for a new Olympic sport: _____",
  "What your GPS is really thinking when it says 'recalculating': _____",
  "The worst thing to find taped under your desk at a new job: _____",
  "A terrible slogan for a mattress store: _____",
  "What clowns do on their day off: _____",
  "The most useless invention of the next 100 years: _____",
  "A bad name for a summer camp: _____",
  "What your refrigerator says about you behind your back: _____"
];

export const ZAPLASH_AFTERDARK_PROMPTS: string[] = [
  "The worst thing to say right after intimacy: _____",
  "A terrible confession to make on a first date: _____",
  "What your partner's search history really looks like: _____",
  "The worst place to leave a pair of dirty underwear: _____",
  "A terrible secret to reveal during truth or dare: _____",
  "The most awkward moment to get a sudden text message: _____",
  "What you shouldn't whisper in someone's ear at a club: _____",
  "A terrible name for a romance novel chapter: _____",
  "What's hidden in the bottom drawer of your nightstand: _____",
  "The worst excuse for getting caught sneaking out at 2 AM: _____",
  "A terrible pickup line to use at a funeral: _____",
  "What your ex is probably doing right now: _____",
  "The most inappropriate song to play on date night: _____",
  "A terrible tattoo to get on your lower back: _____",
  "The worst response to 'I love you': _____",
  "What you shouldn't bring into a hot tub party: _____",
  "A terrible theme for an adult birthday party: _____",
  "The worst thing to overhear through thin hotel walls: _____",
  "What really happens at bachelor parties when the phone cameras off: _____",
  "A bizarre reason to break up with someone after 3 years: _____",
  "The worst topic to bring up at Thanksgiving dinner with the in-laws: _____",
  "What your browser's incognito tab is ashamed of: _____",
  "A terrible nickname your partner calls you in private: _____",
  "The worst thing to drop in a public sauna: _____",
  "A terrible lie to tell on your dating app profile: _____",
  "What you shouldn't do during a couple's massage: _____",
  "The most awkward thing to find in your roommate's closet: _____",
  "A terrible line to use in a breakup text: _____",
  "What people are actually doing on video calls when camera is off: _____",
  "The worst thing to say to your partner's parents on first meeting: _____",
  "A terrible excuse for calling your boss by your spouse's name: _____",
  "The most suspicious stain to find on a couch cushion: _____",
  "What you shouldn't google on your work computer: _____",
  "A terrible gift to give your spouse on your anniversary: _____",
  "The worst thing to wear to a Speed Dating event: _____",
  "What your therapist is secretly writing down during your session: _____",
  "A terrible advice column answer for a broken heart: _____",
  "The most embarrassing object to buy at 3 AM from a 24-hour pharmacy: _____",
  "What you shouldn't say when caught looking at someone's photo: _____",
  "The worst way to propose marriage in public: _____",
  "The worst thing to accidentally like on your ex's Instagram from three years ago: _____",
  "A terrible thing to whisper during a slow dance at a wedding: _____",
  "What your search history says about your 'situationship': _____",
  "The worst nickname to accidentally call a new partner: _____",
  "A red flag you ignored on the third date: _____",
  "What you shouldn't say when your partner asks 'do these jeans make me look weird': _____",
  "The worst thing to be caught doing during a Zoom call with your camera 'off': _____",
  "A terrible excuse for having someone else's clothes in your car: _____",
  "What your group chat really thinks about your new partner: _____",
  "The worst thing to find while snooping through your partner's phone: _____",
  "A bad idea for a 'spicing things up' suggestion that killed the mood instantly: _____"
];

export const ZAPLASH_OFFICE_PROMPTS: string[] = [
  "The worst thing to say during a job interview: _____",
  "A terrible name for a new company mascot: _____",
  "What really happens in the office supply closet after hours: _____",
  "The worst out-of-office auto-reply message: _____",
  "A ridiculous new rule for the break room fridge: _____",
  "What your coworker is really doing during 'mic issues' on a call: _____",
  "The worst icebreaker question for a team-building retreat: _____",
  "A terrible name for a new corporate wellness program: _____",
  "What the CEO actually meant by 'let's circle back': _____",
  "The worst excuse for missing a 9 AM meeting: _____",
  "A bad slogan for a company about to go bankrupt: _____",
  "What's really inside the mystery leftovers in the office fridge: _____",
  "The worst thing to accidentally reply-all to the whole company: _____",
  "A terrible theme for the annual holiday party: _____",
  "What your manager writes in your performance review when they've clearly forgotten who you are: _____",
  "The worst new perk to add to a 'fun' startup culture: _____",
  "A ridiculous excuse for why the printer is broken again: _____",
  "What the vending machine is hiding behind the candy bars: _____",
  "The worst thing to hear on your first day: _____",
  "A terrible name for a conference room: _____",
  "What HR is really investigating this time: _____",
  "The worst way to find out you've been laid off: _____",
  "A bad idea pitched during a brainstorming session that somehow got approved: _____",
  "What your LinkedIn headline really means: _____",
  "The worst thing to overhear through a thin cubicle wall: _____",
  "A ridiculous new dress code policy: _____",
  "What's actually causing the 'unprecedented server outage': _____",
  "The worst gift from a Secret Santa at the office: _____",
  "A terrible new company core value: _____",
  "What everyone's actually doing during 'heads-down focus time': _____",
  "The worst thing a boss has ever said in an all-hands meeting: _____",
  "A bad excuse for not turning your camera on during a meeting: _____",
  "What the new hire found in the desk drawer of the guy they replaced: _____",
  "The worst name for a company newsletter: _____",
  "A ridiculous KPI to measure employee happiness: _____",
  "What's really going on in the 'mandatory fun' committee: _____",
  "The worst thing to say while asking for a raise: _____",
  "A terrible motivational poster for the break room: _____",
  "What the office plant has silently witnessed: _____",
  "The worst way to announce you're quitting: _____",
  "A bad name for the company's new mobile app: _____",
  "What's really being discussed in the meeting that could have been an email: _____",
  "The worst thing to bring to the office potluck: _____",
  "A ridiculous excuse for being 'in the bathroom' for 45 minutes: _____",
  "What the janitor has seen after everyone else goes home: _____"
];

export const ZAPLASH_POPCULTURE_PROMPTS: string[] = [
  "The worst plot twist for a beloved kids' movie sequel: _____",
  "A terrible name for a reality TV dating show: _____",
  "What influencers actually do when the camera stops rolling: _____",
  "The worst caption for a picture-perfect vacation photo: _____",
  "A ridiculous spin-off nobody asked for: _____",
  "What's really behind a celebrity's sudden 'wellness journey': _____",
  "The worst thing a superhero could say during a dramatic rescue: _____",
  "A terrible title for next year's biggest award-show acceptance speech: _____",
  "What's actually trending for all the wrong reasons: _____",
  "The worst thing to find in a movie star's search history: _____",
  "A bad name for a boy band trying a comeback: _____",
  "What a true crime podcast host says right before the ad break: _____",
  "The worst reason a show got cancelled after one season: _____",
  "A ridiculous requirement to become an official 'influencer': _____",
  "What's really inside a celebrity's oddly specific green room request: _____",
  "The worst thing to happen live on air during the evening news: _____",
  "A terrible tagline for a horror movie remake: _____",
  "What a washed-up child star is doing these days: _____",
  "The worst thing an AI chatbot said before it got shut down: _____",
  "A ridiculous rule on a celebrity's tour bus: _____",
  "What's really going on in the group chat of a boy band: _____",
  "The worst thing to happen during a live-streamed wedding: _____",
  "A terrible name for the next viral dance craze: _____",
  "What a talk show host really thinks during the commercial break: _____",
  "The worst way for a streaming show to end its final season: _____",
  "A ridiculous demand in a diva's rider: _____",
  "What's actually funding a mysterious new streaming platform: _____",
  "The worst thing overheard backstage at an award show: _____",
  "A terrible replacement judge for a singing competition: _____",
  "What a video game character mutters when you leave them idle too long: _____",
  "The worst thing a paparazzi photo accidentally caught: _____",
  "A ridiculous new category for next year's awards show: _____",
  "What's really written in a celebrity memoir's deleted chapter: _____",
  "The worst thing an app update secretly added: _____",
  "A terrible plot for the tenth sequel in a superhero franchise: _____",
  "What a game show contestant blurts out under pressure: _____",
  "The worst thing to happen during a live TV cooking segment: _____",
  "A ridiculous fan theory that somehow turned out to be true: _____",
  "What's actually causing your favorite app to crash constantly: _____",
  "The worst thing a celebrity apologized for in a very awkward video: _____",
  "A terrible name for a new streaming service: _____",
  "What a movie villain complains about at their own support group: _____",
  "The worst thing to say in a wedding speech for internet-famous friends: _____",
  "A ridiculous rule at a celebrity's private island: _____",
  "What the algorithm knows about you that you wish it didn't: _____"
];

export const ZAPLASH_FANTASY_PROMPTS: string[] = [
  "The worst spell a wizard could accidentally cast at a dinner party: _____",
  "A terrible name for a dragon trying to seem approachable: _____",
  "What aliens really think when they finally land on Earth: _____",
  "The worst weapon to bring to a medieval sword fight: _____",
  "A ridiculous rule in the wizard school cafeteria: _____",
  "What a superhero complains about most on the job: _____",
  "The worst thing to say to a dragon guarding its treasure: _____",
  "A terrible name for a starship about to explode: _____",
  "What time travelers accidentally leave behind in the past: _____",
  "The worst power-up in a video game that turned out completely useless: _____",
  "A ridiculous requirement to join a secret order of knights: _____",
  "What a robot uprising actually demands first: _____",
  "The worst thing found inside a wizard's spell component pouch: _____",
  "A terrible battle cry for a goblin army: _____",
  "What a vampire lists as their day job on a resume: _____",
  "The worst side effect of drinking a potion of invisibility: _____",
  "A ridiculous new rule for intergalactic customs: _____",
  "What an elf mutters under their breath about humans: _____",
  "The worst thing to hear from your dungeon master mid-campaign: _____",
  "A terrible superhero name that somehow got approved: _____",
  "What a wizard's familiar actually thinks of their owner: _____",
  "The worst monster to find hiding under your bed: _____",
  "A ridiculous excuse a knight gives for fleeing a dragon: _____",
  "What a genie complains about after centuries in a lamp: _____",
  "The worst thing an AI overlord could say to try to seem friendly: _____",
  "A terrible name for a wizard's tower: _____",
  "What a mermaid actually thinks about life on land: _____",
  "The worst curse a witch could put on a small village: _____",
  "A ridiculous item found in a hero's inventory at the end of a quest: _____",
  "What a zombie complains about most during the apocalypse: _____",
  "The worst thing to say while negotiating with a fire-breathing dragon: _____",
  "A terrible name for a spaceship's onboard AI: _____",
  "What a fairy godmother actually charges for her services: _____",
  "The worst side quest a video game could offer: _____",
  "A ridiculous law in a kingdom ruled by talking animals: _____",
  "What a Sasquatch does to relax after a long day of hiding: _____",
  "The worst thing to find in a treasure chest after a hard-won battle: _____",
  "A terrible motto for an evil villain's secret lair: _____",
  "What a ghost haunting a house actually complains about: _____",
  "The worst thing a wizard's apprentice accidentally turned into a frog: _____",
  "A ridiculous rule at an intergalactic diplomatic summit: _____",
  "What a superhero's sidekick really wants for once: _____",
  "The worst thing to whisper to a sleeping dragon: _____",
  "A terrible name for the final boss of a video game: _____",
  "What time travelers are absolutely forbidden from bringing back with them: _____"
];

/** Generic backup answers for the Safety Quip button — vague enough to land on almost any prompt. */
export const ZAPLASH_SAFETY_QUIPS: string[] = [
  "A goat wearing a tiny top hat.",
  "My crushing, unspoken sense of dread.",
  "Whatever the opposite of 'help' is.",
  "A single, judgmental raisin.",
  "Nothing. Absolutely nothing.",
  "Three raccoons in a trench coat.",
  "My student loan debt, somehow.",
  "A guy named Steve. It's always Steve.",
  "Extremely aggressive jazz hands.",
  "The sheer audacity of it all.",
  "A mysterious, ominous hum.",
  "Whatever's left in the fridge.",
  "A conspiracy involving pigeons.",
  "My therapist, and also her therapist.",
  "A tiny horse with big dreams.",
  "Unrelenting, weapons-grade awkwardness.",
  "A rogue Roomba with a grudge.",
  "The last known location of my dignity.",
  "A suspiciously specific apology.",
  "Every regret I've ever had, at once."
];

export const zaplashPacks: ContentPack[] = [
  {
    id: "zaplash-core",
    gameId: "zaplash",
    titleKey: "games.zaplash.packs.core",
    locale: "en",
    nsfw: false,
    payload: { prompts: ZAPLASH_CORE_PROMPTS },
  },
  {
    id: "zaplash-office",
    gameId: "zaplash",
    titleKey: "games.zaplash.packs.office",
    locale: "en",
    nsfw: false,
    payload: { prompts: ZAPLASH_OFFICE_PROMPTS },
  },
  {
    id: "zaplash-popculture",
    gameId: "zaplash",
    titleKey: "games.zaplash.packs.popculture",
    locale: "en",
    nsfw: false,
    payload: { prompts: ZAPLASH_POPCULTURE_PROMPTS },
  },
  {
    id: "zaplash-fantasy",
    gameId: "zaplash",
    titleKey: "games.zaplash.packs.fantasy",
    locale: "en",
    nsfw: false,
    payload: { prompts: ZAPLASH_FANTASY_PROMPTS },
  },
  {
    id: "zaplash-afterdark",
    gameId: "zaplash",
    titleKey: "games.zaplash.packs.afterdark",
    locale: "en",
    nsfw: true,
    payload: { prompts: ZAPLASH_AFTERDARK_PROMPTS },
  },
];
