import type { ContentPack } from "@merky/game-sdk";

export interface MerkadePackPayload {
  trivia: { fact: string; answer: string }[];
  doodleWords: string[];
  majorityPrompts: { prompt: string; options: [string, string] }[];
}

export const corePack: ContentPack = {
  id: "core",
  gameId: "merkade",
  titleKey: "games.merkade.pack.core",
  locale: "en",
  nsfw: false,
  payload: {
    trivia: [
      { fact: "What is the only mammal that cannot jump?", answer: "Elephant" },
      { fact: "What is the national animal of Scotland?", answer: "Unicorn" },
      { fact: "What object did Isaac Newton observe fall from a tree?", answer: "Apple" },
      { fact: "Which planet is known as the Red Planet?", answer: "Mars" },
      { fact: "What is the hardest natural substance on Earth?", answer: "Diamond" },
      { fact: "Which bird is famous for being unable to fly in Antarctica?", answer: "Penguin" },
      { fact: "What metal is liquid at room temperature?", answer: "Mercury" },
      { fact: "How many legs does a spider have?", answer: "Eight" },
      { fact: "What chemical element has the symbol Au?", answer: "Gold" },
      { fact: "What type of tree produces acorns?", answer: "Oak" },
      { fact: "What fruit has its seeds on the outside?", answer: "Strawberry" },
      { fact: "What is the main ingredient in guacamole?", answer: "Avocado" },
      { fact: "Which ocean is the largest on Earth?", answer: "Pacific Ocean" },
      { fact: "What musical instrument has 88 keys?", answer: "Piano" },
      { fact: "Which insect produces honey?", answer: "Honeybee" },
      { fact: "What colors make up the flag of Japan?", answer: "Red and White" },
      { fact: "What component gives plants their green color?", answer: "Chlorophyll" },
      { fact: "What is the largest organ of the human body?", answer: "Skin" },
      { fact: "What continent is the South Pole located on?", answer: "Antarctica" },
      { fact: "What is a group of flamingos called?", answer: "Flamboyance" },
      { fact: "What shape is a standard stop sign?", answer: "Octagon" },
      { fact: "What gas do plants absorb during photosynthesis?", answer: "Carbon Dioxide" },
      { fact: "What is the smallest planet in our solar system?", answer: "Mercury" },
      { fact: "Which egg-laying mammal lives in Australia?", answer: "Platypus" },
    ],
    doodleWords: [
      "a nervous scarecrow",
      "the world's smallest gym",
      "a rocket powered snail",
      "dancing flamingo",
      "sleeping dragon",
      "flying toaster",
      "giant waffle",
      "alien barbecue",
      "pirate penguin",
      "skateboarding dog",
      "disco robot",
      "a sad sandwich",
      "superhero turtle",
      "haunted teapot",
      "dinosaur in a suit",
      "crying onion",
      "sunglasses on a moon",
      "space cactus",
      "confused wizard",
      "melting ice cream",
      "running pizza",
      "banana on skates",
      "magic microphone",
      "detective cat",
    ],
    majorityPrompts: [
      { prompt: "Which is worse to find in your shoe?", options: ["a spider", "a wet sock"] },
      { prompt: "Which superpower would you choose?", options: ["flight", "invisibility"] },
      { prompt: "Where would you spend a weekend?", options: ["mountain cabin", "sunny beach"] },
      { prompt: "Which food could you eat every single day?", options: ["pizza", "tacos"] },
      { prompt: "Would you rather live in...", options: ["the far past", "the far future"] },
      { prompt: "Which pet would you rather adopt?", options: ["mini elephant", "giant hamster"] },
      { prompt: "Which breakfast item reigns supreme?", options: ["pancakes", "waffles"] },
      { prompt: "Which season is better?", options: ["summer", "winter"] },
      { prompt: "Would you rather communicate only via...", options: ["singing", "rhyming"] },
      { prompt: "Which movie genre is superior?", options: ["comedy", "sci-fi"] },
      { prompt: "Would you rather deal with...", options: ["extreme heat", "extreme cold"] },
      { prompt: "Which vehicle is cooler?", options: ["submarine", "spaceship"] },
      { prompt: "Which morning beverage do you need?", options: ["coffee", "tea"] },
      { prompt: "Would you rather have a personal...", options: ["chef", "chauffeur"] },
      { prompt: "Which game type is more fun?", options: ["board games", "video games"] },
      { prompt: "Which movie snack is better?", options: ["butter popcorn", "nachos"] },
    ],
  },
};
